version: '3'
services:
  api:
    build:
      dockerfile: Dockerfile.dev
      context: .
    env_file: ./config/dev.env
    ports:
      - '5000:5000'
    volumes:
      # - /app/api/node_modules
      - .:/app/api
    depends_on:
      - db
      - redis
  db:
    image: 'postgres:latest'
    restart: always
  redis:
    image: 'redis:latest'
    restart: always
