FROM node:alpine

WORKDIR /app/web
COPY ./package.json ./package.json

RUN yarn install
RUN yarn global add nodemon
RUN yarn global add ts-node

COPY .next .next
COPY . .
EXPOSE 3000
CMD ["yarn", "dev"]